// Original RPG sprites. One character is one pixel in a 32×32 canvas.
// Transparent '.', and 8-bit grayscale inks; edit the maps to redraw sprites.
export const palette = { '#': 24, s: 64, m: 112, g: 160, l: 208, w: 248 };
export const characters = [
  ['Soldier', `
......######......
.....#gllllg#.....
....#glwwllgs#....
....##########....
.....#lw#w#l#.....
.....#llllls#.....
......#lmls#......
..##..######......
.#wl##gllllg###....
.#wl#sglwwlg#ms#...
.#wl#sgllllg#mls#..
.#wl#sgggggg#mls#..
..##.########ms#..
..##..#ssss#ms#...
..##..#g##g###....
......#g##gs#.....
.....#ms##sms#....
.....####.####....`],
  ['Lancer', `
..#...............
.#w#..............
.#wl#....#####....
.#wl#...#lllgss#..
..##....########..
..##.....#wl#ls#..
..##.....#lllls#..
..##......####....
..##....##gllg##..
..#######glwlgss#.
..#llsss#glwlgs#..
..######sgllggs#..
..##....#ggggss#..
..##....########..
..##.....#gs#gs#..
..##.....#gs#gs#..
..##....#gss#sgs#.
..##....####.####.`],
  ['Knight', `
........##........
.......#ll##......
......#lggss#.....
.......####.......
......#wllgs#.....
......########....
......#w#s#gs#....
.......#llgs#.....
....##..####......
...#wl##gllg#.....
...#wl#glwlgs#....
...#wl#gggggs#....
.##.##.######.....
#lg#..##gss###....
#lwl##llgllgss##..
#l#llgllllgggsss#.
.#lllgggggggsss#..
..##gllggggss###..
...#g######gs#.#..
...#g#....#gs#....
..#gs#....#sgs#...
..####....#####...`],
  ['Silver ranger', `
.......#####......
......#gglgg#.....
.....#glwllgs#....
.....#g###lgs#....
.....#g#w#lgs#....
......#llls#......
......######...##.
....##gglgss#.#lg#
...#g#glwlgs#..#lg
..#g##glwlgss###lg
..#l##ggggg#lllwlg
...###ssssss####lg
.....#ggggss#..#lg
....#ggggsss#.#lg#
....########..##..
.....#gs#gs#......
.....#gs#gs#......
....#sss#sss#.....
....####.####.....`],
  ['Gold paladin', `
......#....#......
.....#l####l#.....
.....#llwwll#.....
.....########.....
......#w#wls#.....
......#lllss#.....
...############...
..#wll#lwwl#llw#..
..#lgs#lwwl#gls#..
...###glwwlg###...
..####gllllg####..
.#wllw#gggg#wllw#.
.#lwwl######lwwl#.
.#lwwl#ssss#lwwl#.
..#ll#lg##gl#ll#..
...###lg##gl###...
.....#gs##sg#.....
....#lgs##sgl#....
....#####.#####...`],
  ['Bishop mage', `
........##........
.......#wl#.......
......#llgs#......
.....#llggss#.....
....#llgggsss#....
...############...
......#w#wss#..##.
......#sssss#.#wl#
.......####...##..
.....##ggss#..##..
....#glwggss#.##..
...#glwgggsss###..
...#llggggsss#ll#.
....#gggggsss###..
....#glgggssss###.
...#glwggggssss#..
..#glwggggggssss#.
..###############.
.....####.####....`],
  ['Rook berserker', `
.....##....##.....
....#wl#..#lw#....
....#gl####lg#....
.....#llwwll#.....
.....########.....
......#w#wls#.....
......#lmlss#.....
.......####.......
..##.##ggll##.##..
.#wl#ll#llll#ll#l#
#wll#ll#lgll#ll#lg
#wll##lgggggl##llg
.#wl#.#######.#ll#
..##..#sssss#..##.
..##..#g###g#..##.
..##..#gs#gs#..##.
.....#lgs#sgl#....
.....####.####....`],
  ['King', `
.......##.........
...##.#wl#.##.....
...#l##wl##l#.....
...#llwllwll#.....
...##########.....
....#l#w#wls#.....
....#lllllls#.....
.....#lwwls#......
..############....
.#sgg#llwl#ggs#...
.#sgg#lwwl#ggs#...
.#sgg#lwwl#ggs#.#.
.#sgg#llll#ggs##l#
.#sgg######gs#llw#
.#sgg#llll#ggs###.
.#sgg#lwwl#ggs#.#.
.#sgg#lwwl#ggs#.#.
.#sgg#llll#ggs#.#.
.##############.#.
....#####.#####...`],
];

const horse = `
......##....##......
.....#wl#..#lg#.....
.....#ll###lgs#.....
......#llllgss#.....
....##l#wllgss#....
...#llllllgsss#.....
...#llgggggsss#.....
....#####ggsss#.....
.......#glggsss#....
...##.#glwggsss#....
..#ll#glwggggsss#...
..#llggggggggsss#..
...#llgggggggsss#..
....#gggggggss###..
....#g########gs#..
....#g#......#gs#..
...#gs#......#sgs#.
...####......#####.`;
const dragon = `
..#..........#..........
.#g#........#g#.........
.#lg#..##..#gl#.........
.#llg##lg##gll#.........
.#lwlglgggglwl#...##....
..#llggggggll#...#lg#...
...##gggggg##...#lg#....
.....#l#wlg#...#lg#.....
....#llllgg##.#lg#......
...#llllggsss##lg#......
....####glgggssg#.......
......#glwlgggss#.......
.....#glwwlgggsss#......
...##glwwwlggggss#......
..#llglwwlgggggss#......
...##ggllgggggss#.......
....#gggggggss##........
...#llg##llg##..........
...####..####...........`;

export function spriteMarkup() {
  const promoted = characters.slice(0, 4).map(([name, map]) => [`Ascended ${name}`, map]);
  const all = [...characters, ...promoted, ['Dragon horse', horse], ['Dragon king', dragon]];
  const symbols = all.map(([name, map], i) => {
    const rows = map.trim().split('\n');
    const ox = Math.floor((32 - Math.max(...rows.map(r => r.length))) / 2);
    const oy = 30 - rows.length;
    const paths = Object.entries(palette).map(([ink, shade]) => {
      let d = '';
      rows.forEach((row, y) => [...row].forEach((p, x) => {
        if (p === ink) d += `M${ox+x} ${oy+y}h1v1h-1z`;
      }));
      return d ? `<path fill="rgb(${shade},${shade},${shade})" d="${d}"/>` : '';
    }).join('');
    // Promoted units retain their class silhouette and gain a bright winged crest.
    const crest = i >= 8 && i <= 11 ? '<path fill="#181818" d="M2 3h7v2h4v4H9V7H5V5H2zM30 3h-7v2h-4v4h4V7h4V5h3z"/><path fill="#f8f8f8" d="M3 3h5v1H3zM24 3h5v1h-5zM14 2h4v2h2v2h-2v2h-4V6h-2V4h2z"/>' : '';
    const box = crest ? '1 1 30 30' : `${ox-1} ${oy-1} ${32-2*ox+2} ${rows.length+2}`;
    return `  <symbol id="piece-${i+1}" viewBox="${box}"><title>${name}</title>${paths}${crest}</symbol>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" shape-rendering="crispEdges">\n${symbols.join('\n')}\n</svg>\n`;
}
